#!/bin/bash

echo "============================================================"
echo "ComfyUI-UnlimitAI 小说转漫剧工作流"
echo "============================================================"
echo ""
echo "使用方法:"
echo ""
echo "方法 1: ComfyUI 工作流（推荐）"
echo "  1. 启动 ComfyUI"
echo "  2. 加载 workflows/novel_to_drama_complete_workflow.json"
echo "  3. 配置 API Key 和参数"
echo "  4. 运行工作流"
echo ""
echo "方法 2: 命令行快速开始"
echo "  export UNLIMITAI_API_KEY='your-api-key'"
echo "  cd workflows"
echo "  python quick_start.py"
echo ""
echo "文档:"
echo "  - workflows/README.md (快速入门)"
echo "  - workflows/WORKFLOW_GUIDE.md (完整指南)"
echo "  - /Users/aleven/Desktop/UnlimitAI_API_完整文档.md (API 文档)"
echo ""
echo "============================================================"
